### ISSUE TITLE
don't work bat file..

### ISSUE THREAD

**Issue by darongE** [fpoussin/Qt5-MSVC-Static#1]
I tried to run.bat on command window.
I think.. it doensn't work..
I don't know how can build source code..
Explain some steps to build code.

**Comment by fpoussin** [comment]
Hey,

Did you run the run.bat file from the MSVC prompt?
All steps are in the readme file.

**Comment by darongE** [comment]
yeh.. I tried to.. anyway.. Ill try more.. Let you know result.

**Comment by fpoussin** [comment]
Any update?

**Comment by darongE** [comment]
hey! I can't install icu.. I success installing open-ssl.
build_icu.bat file have problem.

**Comment by fpoussin** [comment]
Can you provide some debug output?

**Comment by darongE** [comment]
It works!  when I installed cygwin , it worked.. 
sorry late reply.
![build](https://cloud.githubusercontent.com/assets/3068049/15627560/e95ae628-2522-11e6-81da-820624009643.png)

**Comment by darongE** [comment]
I failed to build qt source code..
It doesn't show "Installing Qt..." 

![build2](https://cloud.githubusercontent.com/assets/3068049/15627740/2feb8c00-2528-11e6-8322-3d2f8ae29426.png)

**Comment by darongE** [comment]
change icu build like this.
SET _CD=%CD%
SET _PATH=%PATH%
SET ICU_SOURCE=%_CD%\icu\source
SET ICU_DIST=%_CD%\icu\icu-build

//REM Building ICU

RD /s /q %ICU_SOURCE%\lib
RD /s /q %ICU_SOURCE%\bin
RD /s /q %ICU_DIST%

SET PATH=%PATH%;C:\cygwin64\bin

CD /D %ICU_SOURCE%
dos2unix *
dos2unix -f configure
for /F %%P in ('cygpath -u %ICU_DIST%') do bash runConfigureICU Cygwin/MSVC -prefix=%%P

make clean
make && make install

CD /D %_CD%
SET PATH=%_PATH%

SET PATH=%PATH%;%ICU_DIST%\bin;%ICU_DIST%\lib
SET INCLUDE=%INCLUDE%;%ICU_DIST%\include
SET LIB=%LIB%;%ICU_DIST%\lib

I think this worked. I refer this blog.
http://pempek.net/articles/2015/10/18/compiling-qt-5-5-1-with-visual-studio-2015/

**Comment by darongE** [comment]
anyway options.bat .. I change like this.
@echo off
//i build qt-everywhere-source-code .. 
set QTVER=5.6.0
set QTDIR=C:\qt-everywhere-opensource-src-%QTVER%
set QTINSTALLDIR=C:\Qt\Qt%QTVER%\5.6\msvc2015_64

set QTBUILDDIR=%QTDIR%\build
SET QMAKESPEC=win32-msvc2015     

set PATH=%PATH%;C:\qt-everywhere-opensource-src-%QTVER%\gnuwin32\bin

**Comment by darongE** [comment]
setup_qt.bat  I change like this.

echo Configuring Qt...
start /W /BELOWNORMAL %QTDIR%\configure.bat -prefix %QTINSTALLDIR% -opensource -release -confirm-license -opengl dynamic -mp -static -qt-libpng -qt-libjpeg -qt-zlib -qt-pcre -no-angle -no-accessibility -nomake examples -nomake tests 
-skip qtwebkit-examples -opensource -openssl -I %SSLINSTALLDIR%\include -L %SSLINSTALLDIR%\lib -icu -I %ICUINSTALLDIR%\include -L %ICUINSTALLDIR%\lib
IF %errorlevel% NEQ 0 exit /b %errorlevel%

**Comment by fpoussin** [comment]
It looks like you just have a problem with your path.

**Comment by darongE** [comment]
really? what  .......OTL

**Comment by fpoussin** [comment]
Yes, also the scripts are actually made for MSYS, not Cygwin.

**Comment by darongE** [comment]
Okey.. I success building qmake .. anyway time to build submodule file.
