### ISSUE TITLE
Typo in VS2017_Win64.lnk

### ISSUE THREAD

**Issue by raygray** [fpoussin/Qt5-MSVC-Static#4]
Thanks for this great timesaver!

There is a typo in VS2017_Win64.lnk comment:
instead of "Open Visual Studio 2017 Tools Command Prompt for targeting x86" should be
"Open Visual Studio 2017 Tools Command Prompt for targeting x64".

**Comment by fpoussin** [comment]
Fixed in 773223ddfdb0b8dc58cd54b7eabd4760ae65144f
Thanks!
